# Generated by Django 2.0.1 on 2019-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.CharField(max_length=2000),
        ),
    ]
