# Generated by Django 2.1.4 on 2019-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32)),
                ('course_code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
    ]
